name: Pybind11 CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  repository_dispatch:
    types: [pybind-wrapper]

jobs:
  mac-build:
    name: Wrapper macOS Build
    runs-on: macos-latest
    strategy:
      matrix:
        pyversion: ["python@3.8", "python@3.9"] # "python@3.7" not supported in Github Actions
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build the macOS wheels
      run: |
        ./build-macos.sh ${{ matrix.pyversion }}
